export const encodeLabels = {
    English: {
        title: 'Base64 Encoder',
        inputPlaceholder: 'Enter text to encode in Base64 here',
        encodedPlaceholder: 'Encoded Base64 text will appear here',
        encodeButton: 'Encode',
        autoMode: 'Auto (Live Mode)',
        fileUploaded: 'Uploaded File',
        encodedResult: 'Encoded Base64 text will appear here',
    },
    한국어: {
        title: 'Base64 인코더',
        inputPlaceholder: 'Base64로 인코딩할 텍스트를 입력하세요',
        encodedPlaceholder: 'Base64로 인코딩된 텍스트가 여기에 표시됩니다',
        encodeButton: '인코드',
        autoMode: '자동 (라이브 모드)',
        fileUploaded: '업로드된 파일',
        encodedResult: 'Base64로 인코딩된 텍스트가 여기에 표시됩니다',
    },
    Español: {
        title: 'Codificador Base64',
        inputPlaceholder: 'Introduce texto para codificar en Base64 aquí',
        encodedPlaceholder: 'El texto codificado en Base64 aparecerá aquí',
        encodeButton: 'Codificar',
        autoMode: 'Automático (Modo en vivo)',
        fileUploaded: 'Archivo Subido',
        encodedResult: 'El texto codificado en Base64 aparecerá aquí',
    },
    Français: {
        title: 'Encodeur Base64',
        inputPlaceholder: 'Entrez le texte à encoder en Base64 ici',
        encodedPlaceholder: 'Le texte encodé en Base64 apparaîtra ici',
        encodeButton: 'Encoder',
        autoMode: 'Automatique (Mode en direct)',
        fileUploaded: 'Fichier Téléchargé',
        encodedResult: 'Le texte encodé en Base64 apparaîtra ici',
    },
    Deutsch: {
        title: 'Base64-Codierer',
        inputPlaceholder: 'Geben Sie hier den zu codierenden Text ein',
        encodedPlaceholder: 'Der codierte Base64-Text wird hier angezeigt',
        encodeButton: 'Codieren',
        autoMode: 'Automatisch (Live-Modus)',
        fileUploaded: 'Hochgeladene Datei',
        encodedResult: 'Der codierte Base64-Text wird hier angezeigt',
    },
    中文: {
        title: 'Base64 编码器',
        inputPlaceholder: '在此处输入要编码为 Base64 的文本',
        encodedPlaceholder: '编码后的 Base64 文本将显示在这里',
        encodeButton: '编码',
        autoMode: '自动（实时模式）',
        fileUploaded: '上传的文件',
        encodedResult: '编码后的 Base64 文本将显示在这里',
    },
    日本語: {
        title: 'Base64 エンコーダー',
        inputPlaceholder: 'Base64にエンコードするテキストをここに入力してください',
        encodedPlaceholder: 'エンコードされたBase64テキストがここに表示されます',
        encodeButton: 'エンコード',
        autoMode: '自動 (ライブモード)',
        fileUploaded: 'アップロードされたファイル',
        encodedResult: 'エンコードされたBase64テキストがここに表示されます',
    },
    हिंदी: {
        title: 'Base64 एन्कोडर',
        inputPlaceholder: 'Base64 में एन्कोड करने के लिए पाठ यहां दर्ज करें',
        encodedPlaceholder: 'एन्कोड किया गया Base64 पाठ यहां दिखाई देगा',
        encodeButton: 'एन्कोड करें',
        autoMode: 'स्वचालित (लाइव मोड)',
        fileUploaded: 'अपलोड की गई फ़ाइल',
        encodedResult: 'एन्कोड किया गया Base64 पाठ यहां दिखाई देगा',
    },
};

export const decodeLabels = {
    English: {
        title: 'Base64 Decoder',
        inputPlaceholder: 'Enter Base64 text to decode here\nFor images, add data:image/png;base64, at the beginning',
        decodedPlaceholder: 'Decoded Base64 text or image will appear here',
        decodeButton: 'Decode',
        autoMode: 'Auto (Live Mode)',
        fileUploaded: 'Uploaded File',
        decodedImage: 'Decoded Image',
    },
    한국어: {
        title: 'Base64 디코더',
        inputPlaceholder: 'Base64 디코딩할 텍스트를 입력하세요\n이미지의 경우 맨 앞에 data:image/png;base64, 추가 필수',
        decodedPlaceholder: '디코딩된 Base64 텍스트 또는 이미지가 여기에 표시됩니다',
        decodeButton: '디코드',
        autoMode: '자동 (라이브 모드)',
        fileUploaded: '업로드된 파일',
        decodedImage: '디코딩된 이미지',
    },
    Español: {
        title: 'Decodificador Base64',
        inputPlaceholder: 'Introduce texto Base64 para decodificar aquí\nPara imágenes, añade data:image/png;base64, al principio',
        decodedPlaceholder: 'El texto o imagen decodificada en Base64 aparecerá aquí',
        decodeButton: 'Decodificar',
        autoMode: 'Automático (Modo en vivo)',
        fileUploaded: 'Archivo Subido',
        decodedImage: 'Imagen Decodificada',
    },
    Français: {
        title: 'Décodeur Base64',
        inputPlaceholder: 'Entrez le texte Base64 à décoder ici\nPour les images, ajoutez data:image/png;base64, au début',
        decodedPlaceholder: 'Le texte ou l\'image décodé(e) en Base64 apparaîtra ici',
        decodeButton: 'Décoder',
        autoMode: 'Automatique (Mode en direct)',
        fileUploaded: 'Fichier Téléchargé',
        decodedImage: 'Image Décodée',
    },
    Deutsch: {
        title: 'Base64-Decoder',
        inputPlaceholder: 'Geben Sie hier den Base64-Text zum Dekodieren ein\nFür Bilder fügen Sie data:image/png;base64, am Anfang hinzu',
        decodedPlaceholder: 'Der dekodierte Base64-Text oder das Bild wird hier angezeigt',
        decodeButton: 'Dekodieren',
        autoMode: 'Automatisch (Live-Modus)',
        fileUploaded: 'Hochgeladene Datei',
        decodedImage: 'Dekodiertes Bild',
    },
    中文: {
        title: 'Base64 解码器',
        inputPlaceholder: '在此处输入要解码的 Base64 文本\n对于图像，请在前面添加 data:image/png;base64,',
        decodedPlaceholder: '解码后的 Base64 文本或图像将显示在这里',
        decodeButton: '解码',
        autoMode: '自动（实时模式）',
        fileUploaded: '上传的文件',
        decodedImage: '解码后的图像',
    },
    日本語: {
        title: 'Base64 デコーダー',
        inputPlaceholder: 'デコードするBase64テキストをここに入力してください\n画像の場合は先頭に data:image/png;base64, を追加してください',
        decodedPlaceholder: 'デコードされたBase64テキストまたは画像がここに表示されます',
        decodeButton: 'デコード',
        autoMode: '自動 (ライブモード)',
        fileUploaded: 'アップロードされたファイル',
        decodedImage: 'デコードされた画像',
    },
    हिंदी: {
        title: 'Base64 डिकोडर',
        inputPlaceholder: 'डिकोड करने के लिए Base64 पाठ यहां दर्ज करें\nचित्रों के लिए, शुरुआत में data:image/png;base64, जोड़ें',
        decodedPlaceholder: 'डिकोड किया हुआ Base64 पाठ या छवि यहां दिखाई देगा',
        decodeButton: 'डिकोड करें',
        autoMode: 'स्वचालित (लाइव मोड)',
        fileUploaded: 'अपलोड की गई फ़ाइल',
        decodedImage: 'डिकोड किया गया छवि',
    },
};
